### ISSUE TITLE
-h and --help does not work

### ISSUE THREAD

**Issue by cweiske** [c9s/MiniPear#1]
When running

```
$ minipear --help
$ minipear -h
```

I expect the help screen to be shown. Unfortunately, it does not (I have to use "help" only).

Maybe you want to use PEAR's Console_CommandLine package for CLI option parsing, which automatically generates the help screen.

**Comment by c9s** [comment]
Hi you can simply run: 

   $ Minipear 

This will output the help message and command list.

I will add these common options to the new version CLIFramework.

Thanks! :)

[Sent from iPhone]

Christian Weiskereply@reply.github.com 於 2012/1/28 2:16 寫道：

**Comment by c9s** [comment]
-h and --help works now. :-)
