### ISSUE TITLE
PHP Fatal error:  Call to undefined function MiniPear\curl_init()

### ISSUE THREAD

**Issue by annunaki2k2** [c9s/MiniPear#10]
Trying to mirror any pear repository, I get the following error:

mirror ~ # minipear mirror pear.corneltek.com
Starting mirror pear.corneltek.com...
Channel root: /root/.minipear/pear/channels/pear.corneltek.com
PHP Notice:  Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Notice:  Use of undefined constant CURLOPT_URL - assumed 'CURLOPT_URL' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Notice:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Notice:  Use of undefined constant CURLOPT_FRESH_CONNECT - assumed 'CURLOPT_FRESH_CONNECT' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Notice:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Notice:  Use of undefined constant CURLOPT_FORBID_REUSE - assumed 'CURLOPT_FORBID_REUSE' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Notice:  Use of undefined constant CURLOPT_TIMEOUT - assumed 'CURLOPT_TIMEOUT' in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2
PHP Fatal error:  Call to undefined function MiniPear\curl_init() in phar:///usr/bin/minipear/MiniPear/CurlDownloader.php on line 2

Unfortunately I'm not particularly familiar with the inner workings of minipear to be able to debug it further. Am I simply missing a dependency?

Thanks in advance for any help,

**Comment by c9s** [comment]
yeah you need curl extension to be enabled.  and please make sure if have the latest curl extension.

**Comment by annunaki2k2** [comment]
Perfect - that got it.

Many thanks.
