### ISSUE TITLE
Latest MiniPear version from corneltek fails with "Entry package.xml does not exist"

### ISSUE THREAD

**Issue by annunaki2k2** [c9s/MiniPear#11]
Is there any chance you'd be able to roll a new release and push it to the corneltek repository? The current one seems to be missing the support for "package2.xml" files.

Thanks,

**Comment by c9s** [comment]
Hi you may use git clone this repo, and you will get the latest version

[Sent from iPhone]

**Comment by annunaki2k2** [comment]
Sure, I was thinking to do that, but thought I'd suggest it anyway as the one that is currently in the repository is unable to mirror pear.php.net, and that is the reason most people would probably want to use minipear :-)

**Comment by c9s** [comment]
Just updated the pear channel.

please check out: http://pear.corneltek.com/

While the domain name is changing its IP, you might need to wait for minutes. :)

**Comment by c9s** [comment]
I just updated the install instruction, please use wget to download the latest executable.
