### ISSUE TITLE
--version does not work

### ISSUE THREAD

**Issue by cweiske** [c9s/MiniPear#2]
I cannot get the current version of MiniPear by running

```
$ minipear --version
```

**Comment by c9s** [comment]
Which is not support currently, but i will add this feature later. :)

[Sent from iPhone]

Christian Weiskereply@reply.github.com 於 2012/1/28 2:17 寫道：

**Comment by c9s** [comment]
Hi! I've added --version option to CLIFramework, it should work now. :-)
