### ISSUE TITLE
Downloading zustellzentrum.cweiske.de fails

### ISSUE THREAD

**Issue by cweiske** [c9s/MiniPear#3]
I have my own channel server on http://zustellzentrum.cweiske.de/ - MiniPear totally fails to download it. It even saves 404 status pages! I suggest you check the REST version before trying to download files that do not exist in older REST versions.

```
./minipear mirror zustellzentrum.cweiske.de
Starting mirror zustellzentrum.cweiske.de...
Channel root: /home/cweiske/.minipear/pear/channels/zustellzentrum.cweiske.de
xml file load failed.
Getting package list...
27 packages to mirror.
Mirroring package info section...
xml file load failed.
xml file load failed.
```

```
$ cat ~/.minipear/pear/channels/zustellzentrum.cweiske.de/Chiara_PEAR_Server_REST/c/categories.xml
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /Chiara_PEAR_Server_REST/c/categories.xml was not found on this server.</p>
<hr>
<address>Apache/2.2.16 (Debian) Server at zustellzentrum.cweiske.de Port 80</address>
</body></html>
```

**Comment by c9s** [comment]
Seems like you are running a REST1.0 that does not support categories.xml, I just found a document refer this: http://pear.php.net/manual/en/core.rest.php

**Comment by cweiske** [comment]
Yes. I wrote that document :) http://zustellzentrum.cweiske.de/channel.xml indicates that it's REST 1.0 only.

**Comment by cweiske** [comment]
my channel does not exist anymore, so no need to keep this open.
